# Generated by Django 4.2.1 on 2023-06-08 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Бенд')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Бренди',
                'verbose_name_plural': 'Бренди',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категорії')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорії',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Найменування')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('annotation', models.TextField(max_length=500, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотографія')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('provider', models.PositiveIntegerField(blank=True, null=True, verbose_name='Поставщик')),
                ('full_stock', models.IntegerField(default=0, verbose_name='Стандарт наявності')),
                ('article', models.CharField(blank=True, max_length=20, verbose_name='Артикул')),
                ('price_opt', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ціна ОПТ')),
                ('price_b2c', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ціна Роздріб')),
                ('price_drop', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ціна DROP')),
                ('price_mrc', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='МРЦ')),
                ('opt_stock', models.IntegerField(default=0, verbose_name='Опт наявність')),
                ('b2c_stock', models.IntegerField(default=0, verbose_name='Роздріб наявність')),
                ('drop_stock', models.IntegerField(default=0, verbose_name='DROP наявність')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.brand', verbose_name='Бренд')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.category', verbose_name='Категорія')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Товари',
                'verbose_name_plural': 'Товари',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
