# Generated by Django 4.2.1 on 2023-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='provider',
            field=models.CharField(blank=True, max_length=255, verbose_name='Поставщик'),
        ),
    ]
