# Generated by Django 4.2.1 on 2023-06-21 10:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_good_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='URL'),
        ),
    ]
